# .github/workflows/scrape.yml
name: Scrapy every 6h

permissions:
  contents: write

on:
  schedule:
    - cron: '0 */6 * * *'   # cada 6 horas UTC
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Instalamos pysentimiento primero para fijar su versión de transformers
          pip install pysentimiento==0.2.0
          # Ahora el resto desde requirements.txt; pip elegirá tokenizers<0.11
          pip install -r requirements.txt

      - name: Run scraper
        run: scrapy crawl titulares

      - name: Commit and push results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git add noticias.csv noticias.db
          git commit -m "🤖 Actualización automática de scraping $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No hay cambios que commitear"
          git push origin HEAD:main
